# Generated by Django 3.2 on 2021-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210502_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='embedding',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
